# Generated by Django 3.0 on 2020-07-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200703_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movenotification',
            name='diff_days',
        ),
        migrations.RemoveField(
            model_name='movenotification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='movenotification',
            name='start_date',
        ),
    ]
