# Generated by Django 3.0 on 2020-07-02 12:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('target', models.CharField(choices=[('everyone', 'EVERYONE'), ('gender', 'GENDER'), ('nationality', 'NATIONALITY'), ('residence', 'RESIDENCE')], default='everyone', max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read_by_host', models.BooleanField(default=False)),
                ('is_read_by_guest', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
