# Generated by Django 2.2.4 on 2019-09-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='continent_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
