# Generated by Django 3.0 on 2020-02-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_main', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models.upload_image)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models.upload_thumbnail)),
                ('app_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models.upload_app_thumbnail)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('push_token', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('distance', models.IntegerField(blank=True, default=0, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=15, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=300, null=True)),
                ('app_avatar_url', models.CharField(blank=True, max_length=300, null=True)),
                ('country_phone_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_verified_phone_number', models.BooleanField(default=False)),
                ('is_verified_email_address', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True)),
                ('fbId', models.CharField(blank=True, max_length=60, null=True)),
                ('appleId', models.CharField(blank=True, max_length=80, null=True)),
                ('is_dark_mode', models.BooleanField(default=True)),
                ('is_hide_photos', models.BooleanField(default=False)),
                ('is_hide_trips', models.BooleanField(default=False)),
                ('is_hide_coffees', models.BooleanField(default=False)),
                ('is_hide_cities', models.BooleanField(default=False)),
                ('is_hide_countries', models.BooleanField(default=False)),
                ('is_hide_continents', models.BooleanField(default=False)),
                ('is_auto_location_report', models.BooleanField(default=True)),
                ('send_instagram', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_email', models.EmailField(blank=True, default='', max_length=200, null=True)),
                ('send_kakao', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_facebook', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_snapchat', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_line', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_wechat', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_kik', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_vk', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_whatsapp', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_twitter', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_youtube', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_telegram', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_behance', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_linkedin', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_pinterest', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_vine', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_tumblr', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('blocked_user', models.ManyToManyField(blank=True, related_name='_profile_blocked_user_+', to='users.Profile')),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCity', to='locations.City')),
                ('current_continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentContinent', to='locations.Continent')),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCountry', to='locations.Country')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationality', to='locations.Country')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence', to='locations.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.Avatar')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
