# Generated by Django 2.2.4 on 2019-09-21 16:40

from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='app_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=users.models.upload_app_thumbnail),
        ),
    ]
