# Generated by Django 2.2.4 on 2019-12-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191205_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hide_photos',
            field=models.BooleanField(default=False),
        ),
    ]
