# Generated by Django 2.2.4 on 2019-12-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_hide_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_token',
            field=models.TextField(default=''),
        ),
    ]
