# Generated by Django 2.2.4 on 2019-09-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_app_avatarlurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='app_avatarlUrl',
            new_name='app_avatarl_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatarUrl',
            new_name='avatar_url',
        ),
    ]
