# Generated by Django 3.0 on 2019-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191211_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='user_blocked', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocking_user',
            field=models.ManyToManyField(blank=True, related_name='user_blocking', to='users.Profile'),
        ),
    ]
