# Generated by Django 3.0 on 2019-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191215_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocking_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='_profile_blocked_user_+', to='users.Profile'),
        ),
    ]
