# Generated by Django 3.0 on 2019-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191216_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
