# Generated by Django 3.0 on 2019-12-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191223_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appleId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
