# Generated by Django 3.0 on 2019-12-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_appleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appleId',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
