# Generated by Django 3.0 on 2019-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191227_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appleId',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
