# Generated by Django 3.0 on 2019-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191227_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appleId',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fbId',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
